[package]
name = "smart-wallets-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zephyr-sdk = { version = "0.1.7" }
stellar-strkey = "0.0.8"
serde = { version = "1.0", features = ["derive"] }
stellar-xdr = { version = "20.1.0", features = ["next", "curr", "serde", "base64"] }

[dev-dependencies]
zephyr-sdk = { version = "0.1.7", features = ["testutils"] }
tokio = { version = "1.0", features = ["full"] }
ledger-meta-factory = { version = "0.1.1", features = [] }

# [dev-dependencies.stellar-xdr]
# version = "=20.1.0"
# features = ["next", "curr", "serde", "base64"]

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
