[package]
name = "smart-wallets-data"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
zephyr-sdk = { version = "0.2.1" }
stellar-strkey = "0.0.8"
serde = { version = "1.0", features = ["derive"] }
stellar-xdr = { version = "21.2.0", features = [
    "next",
    "curr",
    "serde",
    "base64",
] }

[dev-dependencies]
zephyr-sdk = { version = "0.2.1", features = ["testutils"] }
tokio = { version = "1.0", features = ["full"] }
ledger-meta-factory = { version = "0.1.2", features = [] }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
